import AboutMe from '@/components/AboutMe';
import Banner from '@/components/Banner';
import Companies from '@/components/Companies';
import Contact from '@/components/Contact';
import Layout from '@/components/Layout';
import Portfolio from '@/components/Portfolio';
import Services from '@/components/Services';
import Toolbelt from '@/components/Toolbelt';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <Banner></Banner>
          <Services></Services>
          <div className="mx-auto max-w-[1200px]">
            <AboutMe></AboutMe>
          </div>
          <Toolbelt></Toolbelt>
          <Portfolio></Portfolio>
          <Companies></Companies>
          <Contact></Contact>
        </main>
      </Layout>
    </>
  );
}
